# Generated by Django 4.2.6 on 2023-10-09 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0003_remove_post_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="reply_to",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="post.post"
            ),
        ),
    ]
