# Generated by Django 4.2.6 on 2023-10-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_post_just_a_share_alter_post_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.TextField(null=True),
        ),
    ]
