# Generated by Django 4.2.6 on 2023-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.TextField(default=""),
        ),
    ]
