# Generated by Django 4.2.6 on 2023-10-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0008_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(to="post.post"),
        ),
    ]
