# Generated by Django 4.2.6 on 2023-10-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0010_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.TextField(blank=True, default=""),
        ),
    ]
