# Generated by Django 4.2.6 on 2023-10-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0011_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="_visibility",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="just_a_share",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                editable=False, related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="reply_to",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reply",
                to="post.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.TextField(blank=True, default="", editable=False),
        ),
    ]
