# Generated by Django 4.2.6 on 2023-10-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0013_post_tags_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="_visibility",
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
