# Generated by Django 4.2.6 on 2023-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0014_tag__visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="_visibility",
            field=models.BigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags_new",
            field=models.ManyToManyField(related_name="tags", to="post.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="_visibility",
            field=models.BigIntegerField(default=1, editable=False),
        ),
    ]
