# Generated by Django 4.2.6 on 2023-11-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0015_alter_post__visibility_alter_post_tags_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="profanity",
            field=models.BooleanField(default=False),
        ),
    ]
