# Generated by Django 4.2.6 on 2023-11-11 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0016_post_profanity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
