# Generated by Django 4.2.6 on 2023-11-16 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0017_remove_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="popularity",
        ),
    ]
