# Generated by Django 4.2.6 on 2023-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_conversation_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
