# Generated by Django 4.2.6 on 2023-10-09 09:46

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(
                blank=True,
                default="default.png",
                null=True,
                upload_to=user.models.get_upload_path_avatars,
            ),
        ),
    ]
