# Generated by Django 4.2.6 on 2023-10-09 10:43

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(
                blank=True,
                default="/avatars/default.png",
                null=True,
                upload_to=user.utils.get_upload_path_avatars,
            ),
        ),
    ]
