# Generated by Django 4.2.6 on 2023-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_userprofile_conversations"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="messages",
            field=models.ManyToManyField(
                related_name="messages", to="user.chatmessage"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
