# Generated by Django 4.2.6 on 2023-10-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_conversation_created_conversation_messages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="users",
            field=models.ManyToManyField(related_name="users", to="user.userprofile"),
        ),
    ]
