# Generated by Django 4.2.6 on 2023-10-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_remove_conversation_author_remove_conversation_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="conversations",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="conversations",
            field=models.ManyToManyField(
                related_name="conversations", to="user.conversation"
            ),
        ),
    ]
