# Generated by Django 4.2.6 on 2023-10-15 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0017_alter_chatmessage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-time_sent"]},
        ),
    ]
