# Generated by Django 4.2.6 on 2023-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_alter_chatmessage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="premium_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="premium_time",
            field=models.DateTimeField(null=True),
        ),
    ]
