# Generated by Django 4.2.6 on 2023-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_alter_chatmessage_time_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="time_sent",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="premium_time",
            field=models.DateField(null=True),
        ),
    ]
