# Generated by Django 4.2.6 on 2023-10-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_alter_chatmessage_time_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="images",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
