# Generated by Django 4.2.6 on 2023-10-16 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_chatmessage_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="images",
        ),
    ]
