# Generated by Django 4.2.6 on 2023-10-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0023_remove_chatmessage_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage_e",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_sender", models.BinaryField()),
                ("body_receiver", models.BinaryField()),
                ("time_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-time_sent"],
            },
        ),
    ]
