# Generated by Django 4.2.6 on 2023-10-20 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0024_chatmessage_e"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage_e",
        ),
    ]
