# Generated by Django 4.2.6 on 2023-10-20 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0010_alter_tag_options"),
        ("user", "0025_delete_chatmessage_e"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="following",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following_t",
            field=models.ManyToManyField(to="post.tag"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following_u",
            field=models.ManyToManyField(
                blank=True, related_name="following_u", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="posts",
            field=models.ManyToManyField(null=True, to="post.post"),
        ),
    ]
