# Generated by Django 4.2.6 on 2023-10-20 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0026_remove_userprofile_following_userprofile_following_t_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="following_u",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="following_u", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
