# Generated by Django 4.2.6 on 2023-10-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0011_alter_post_tags"),
        ("user", "0027_remove_userprofile_following_u_userprofile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following_t",
            field=models.ManyToManyField(
                blank=True, related_name="following_t", to="post.tag"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="posts",
            field=models.ManyToManyField(blank=True, to="post.post"),
        ),
        migrations.CreateModel(
            name="UserProfileSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notifications_follow", models.BooleanField(default=True)),
                ("notifications_like", models.BooleanField(default=True)),
                ("notifications_share", models.BooleanField(default=True)),
                ("notifications_tags", models.BooleanField(default=True)),
                ("notifications_message", models.BooleanField(default=True)),
                ("notifications_to", models.CharField(max_length=5)),
                ("filter_explicit", models.BooleanField(default=True)),
                ("public_tags", models.BooleanField(default=True)),
                ("public_message", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
    ]
