# Generated by Django 4.2.6 on 2023-10-21 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("user", "0029_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="city",
        ),
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.address",
            ),
        ),
    ]
