# Generated by Django 4.2.6 on 2023-10-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0030_remove_address_city_address_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="_visibility",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofilesettings",
            name="user",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.userprofile",
            ),
        ),
    ]
