# Generated by Django 4.2.6 on 2023-10-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0014_tag__visibility"),
        ("user", "0031_userprofile__visibility_alter_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="_visibility",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="posts",
            field=models.ManyToManyField(blank=True, editable=False, to="post.post"),
        ),
    ]
