# Generated by Django 4.2.6 on 2023-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0032_alter_userprofile__visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilesettings",
            name="two_factor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="two_factor_method",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="_visibility",
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="userprofilesettings",
            name="notifications_to",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
