# Generated by Django 4.2.6 on 2023-11-05 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0034_userprofile__prk_userprofile__puk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilesettings",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="u",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
